#!/usr/bin/env bash
# AEGIS — Cloud Agent install phase.
# Idempotent, one-time repository bootstrap that creates durable state:
# PostgreSQL 16, the aegis database (schema + DB-level triggers/views/guards),
# dependencies, generated Prisma client, and demo seed data.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PGVER=16
DB_NAME=aegis
DB_USER=aegis
DB_PASS=aegis_dev_password
DB_PORT=5432
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:${DB_PORT}/${DB_NAME}"

# 1. PostgreSQL 16 (durable system dependency; skipped when already present).
if ! command -v pg_ctlcluster >/dev/null 2>&1 || ! dpkg-query -W -f='${Status}' "postgresql-${PGVER}" 2>/dev/null | grep -q "install ok installed"; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "postgresql-${PGVER}" "postgresql-contrib-${PGVER}"
fi

# Ensure the expected major-version cluster exists.
if ! command -v pg_createcluster >/dev/null 2>&1; then
  echo "pg_createcluster is required but not available after PostgreSQL install." >&2
  exit 1
fi
if ! pg_lsclusters -h 2>/dev/null | awk '{print $1, $2}' | grep -qx "$PGVER main"; then
  sudo pg_createcluster "$PGVER" main --start-conf=manual
fi

# 2. Bring the cluster up so we can provision it (start.sh owns per-boot startup).
sudo pg_ctlcluster "$PGVER" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  pg_isready -q -h localhost -p "$DB_PORT" && break
  sleep 1
done

# 3. Role, database, and required extensions.
sudo -u postgres psql -p "$DB_PORT" -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}' SUPERUSER;
  END IF;
END \$\$;
SQL
sudo -u postgres psql -p "$DB_PORT" -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 \
  || sudo -u postgres createdb -p "$DB_PORT" -O "$DB_USER" "$DB_NAME"
sudo -u postgres psql -p "$DB_PORT" -d "$DB_NAME" \
  -c "CREATE EXTENSION IF NOT EXISTS pgcrypto; CREATE EXTENSION IF NOT EXISTS pg_trgm;"

# 4. Local dev .env (gitignored; regenerated on a fresh checkout).
if [ ! -f "$REPO_ROOT/.env" ]; then
  cat > "$REPO_ROOT/.env" <<ENV
# Generated by .cursor/install.sh for local Cloud Agent development.
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=${DB_NAME}
POSTGRES_PORT=${DB_PORT}
DATABASE_URL=${DATABASE_URL}
BETTER_AUTH_SECRET=$(openssl rand -base64 32)
BETTER_AUTH_URL=http://localhost:3000
NODE_ENV=development
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_TELEMETRY_DISABLED=1
ENV
fi

# 5. Dependencies + Prisma client. Pin pnpm 10 — pnpm 11 ignores this repo's
#    pnpm.overrides block and fails --frozen-lockfile (see CLAUDE.md).
export COREPACK_ENABLE_DOWNLOAD_PROMPT=0
corepack prepare pnpm@10.33.3 --activate >/dev/null 2>&1 || true
pnpm install --frozen-lockfile
pnpm db:generate

# 6. Sync the schema (prisma db push is the repo's fresh-DB workflow).
pnpm db:push

# 7. DB-level augmentation that `db push` does not create: audit triggers,
#    the null-safe trigger patch, dashboard views, RBIA guards, and indexes.
#    Applied by hand per docs; guarded on the trigger function so re-runs skip.
#    RLS policy files are intentionally NOT applied (dead code — see docs).
if ! psql "$DATABASE_URL" -tAc "SELECT 1 FROM pg_proc WHERE proname='audit_trigger_function'" | grep -q 1; then
  # Apply all augmentation in one transaction so a failure cannot leave a
  # partially-augmented database that later runs would skip.
  psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -q <<SQL
BEGIN;
\i prisma/migrations/20260209015123_audit_trigger/migration.sql
\i prisma/migrations/20260209220425_add_remaining_audit_triggers/migration.sql
\i prisma/migrations/20260826_audit_trigger_null_safe.sql
\i prisma/migrations/20260209_dashboard_views.sql
\i prisma/migrations/20260222_rbia_db_guards.sql
-- Observation lifecycle indexes only (the file's RLS/grant tail targets a
-- role that this environment does not create).
CREATE INDEX IF NOT EXISTS idx_observation_repeat_detection ON "Observation" ("tenantId","branchId","auditAreaId",status) WHERE status='CLOSED';
CREATE INDEX IF NOT EXISTS idx_observation_title_trgm ON "Observation" USING gin (title gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_timeline_observation_ordered ON "ObservationTimeline" ("observationId","createdAt");
CREATE INDEX IF NOT EXISTS idx_observation_version ON "Observation" (id, version);
COMMIT;
SQL
fi

# 8. Seed demo data only when the database is empty.
USER_COUNT="$(psql "$DATABASE_URL" -tAc 'SELECT count(*) FROM "User"' 2>/dev/null || echo 0)"
if [ "${USER_COUNT:-0}" = "0" ]; then
  pnpm db:seed
fi

echo "AEGIS install complete."
